SELECT HACKER_ID, 
       NAME, 
       CHALLENGES_CREATED 
FROM (
    SELECT H.HACKER_ID, 
           H.NAME, 
           CHALLENGES_CREATED,
           MAX(CHALLENGES_CREATED) 
           OVER (ORDER BY 1) AS MX_CHLNG, 
           COUNT(CHALLENGES_CREATED) 
    OVER(PARTITION BY CHALLENGES_CREATED) AS NO_OF_COMMON_CHLNG_HCKR
    FROM HACKERS H
    JOIN (
        SELECT DISTINCT HACKER_ID, 
                        COUNT(CHALLENGE_ID) OVER (PARTITION BY HACKER_ID) AS CHALLENGES_CREATED
        FROM CHALLENGES
    ) C
    ON H.HACKER_ID=C.HACKER_ID) A
WHERE NO_OF_COMMON_CHLNG_HCKR=1 
OR (
    CHALLENGES_CREATED>=MX_CHLNG 
    AND NO_OF_COMMON_CHLNG_HCKR!=1
)
ORDER BY CHALLENGES_CREATED DESC, HACKER_ID;